#!/bin/bash
#
# "Remind In" - schedule a popup reminder in X minutes or at a specific time
#

if [ "$2" = "" ]; then
        echo "usage: rin <minutes|time> <text>"
        echo "   ex: rin +30   Check the turkey"
        echo "   ex: rin 16:00 Watch hockey"
        exit 1
fi
if [ "`pgrep atd`" = "" ]; then
        echo "error: atd is not running"
        exit 2
fi
if [ "`which notify-send`" = "" ]; then
        echo "error: libnotify is not installed"
        exit 2
fi

time=$1
atcmd="at $time"
if [ "${time:0:1}" = "+" ]; then
    if [ "${time:0:-1}" = "m" ]; then
        atcmd="at now + ${time:1:-1} min"
        echo "notify-send -i info \"Reminder\" \"$*\"" | $atcmd
        atq
    else
        sleep ${time:1:-1} &
        notify-send -i info "Reminder: " $2
    fi
fi
